### ISSUE TITLE
Running upf in dpdk mode Hyperlink not working

### ISSUE THREAD

**Issue by Alt-Shivam** [canonical/sdcore-upf-k8s-operator#149]
On main README.md 
[How-to: Running UPF in DPDK mode](https://canonical-charmed-5g.readthedocs-hosted.com/en/latest/how-to/running_upf_in_dpdk_mode/). 
link is not working.

**Comment by markbeierl** [comment]
Hello, and thank you for reporting this. At this time, DPDK is still a work in progress, so we have removed that particular section. There is this PR https://github.com/canonical/charmed-5g/pull/164 which is being used to track our work.

**Comment by markbeierl** [comment]
In the meantime, you may join in Matrix to ask questions: https://matrix.to/#/#charmhub-charmed5g:ubuntu.com

**Comment by markbeierl** [comment]
Resolved in #158
